const productos = [
    {id: 1, nombre: 'Acelgas', descripcion: 'Acelgas x manojo', precio: 15.9, unidad: '1pz', imagen: 'acel.png', departamento: 'Frutas y Verduras' },
{id: 2, nombre: 'Aguacate en malla', descripcion: 'Aguacate en malla', precio: 39.9, unidad: '1pz', imagen: 'aguacate_mall.png', departamento: 'Frutas y Verduras' },
{id: 3, nombre: 'Ajo extra ', descripcion: 'Ajo extra x kg', precio: 189.9, unidad: '1pz', imagen: 'ajo.png', departamento: 'Frutas y Verduras' },
{id: 4, nombre: 'Apio ', descripcion: 'Apio x kg', precio: 29.9, unidad: '1pz', imagen: 'apio.png', departamento: 'Frutas y Verduras' },
{id: 5, nombre: 'Brocoli ', descripcion: 'Brocoli x kg', precio: 69.9, unidad: 'kg', imagen: 'brocoli.png', departamento: 'Frutas y Verduras' },
{id: 6, nombre: 'Calabacita', descripcion: 'Calabacita', precio: 18.9, unidad: 'kg', imagen: 'calabacita.png', departamento: 'Frutas y Verduras' },
{id: 7, nombre: 'Cebolla en malla', descripcion: 'Cebolla en malla', precio: 14.9, unidad: 'kg', imagen: 'cebo_ma.png', departamento: 'Frutas y Verduras' },
{id: 8, nombre: 'Cebolla Morada', descripcion: 'Cebolla Morada', precio: 49.9, unidad: '1kg', imagen: 'cebo_mor.png', departamento: 'Frutas y Verduras' },
{id: 9, nombre: 'Champiñon Monte Blanco', descripcion: 'Champiñon Blanco Monte Blanco 450 gr', precio: 64.9, unidad: '1pz', imagen: 'champinon_bco.png', departamento: 'Frutas y Verduras' },
{id: 10, nombre: 'Chile poblano ', descripcion: 'Chile poblano x kg', precio: 56.9, unidad: '1pz', imagen: 'chile_pobl.png', departamento: 'Frutas y Verduras' },
{id: 11, nombre: 'Cilantro', descripcion: 'Cilantro x manojo', precio: 16.9, unidad: '1pz', imagen: 'cilantro.png', departamento: 'Frutas y Verduras' },
{id: 12, nombre: 'Epazote', descripcion: 'Epazote de 40 grs', precio: 14.9, unidad: '1pz', imagen: 'epazote.png', departamento: 'Frutas y Verduras' },
{id: 13, nombre: 'Espinacas', descripcion: 'Espinacas x manojo', precio: 19.9, unidad: '1pz', imagen: 'espinacas.png', departamento: 'Frutas y Verduras' },
{id: 14, nombre: 'Frambuesa ', descripcion: 'Frambuesa 170 grs', precio: 39.9, unidad: '1pz', imagen: 'framb.png', departamento: 'Frutas y Verduras' },
{id: 15, nombre: 'Germinado de Alfalfa', descripcion: 'Germinado de Alfalfa 100 gr', precio: 36.9, unidad: '1pz', imagen: 'germinado_alfa.png', departamento: 'Frutas y Verduras' },
{id: 16, nombre: 'Hierbabueba', descripcion: 'Hierbabuena 40 grs', precio: 14.9, unidad: '1pz', imagen: 'hierbabuena.png', departamento: 'Frutas y Verduras' },
{id: 17, nombre: 'Kiwi ', descripcion: 'kiwi x kg', precio: 899.9, unidad: '1pz', imagen: 'kiwi.png', departamento: 'Frutas y Verduras' },
{id: 18, nombre: 'Lechuga bola', descripcion: 'Lechuga Bola x pieza', precio: 29.9, unidad: '1pz', imagen: 'lechuga_bola.png', departamento: 'Frutas y Verduras' },
{id: 19, nombre: 'Limon agrio', descripcion: 'Limon agrio x kg', precio: 28.9, unidad: 'kg', imagen: 'limo_agrio.png', departamento: 'Frutas y Verduras' },
{id: 20, nombre: 'Mango ATAULFO', descripcion: 'Mango ATAULFO x kg', precio: 49.9, unidad: 'kg', imagen: 'mang_atau.png', departamento: 'Frutas y Verduras' },
{id: 21, nombre: 'Manzana Golden', descripcion: 'Manzana Golden Delicious x kg', precio: 49.9, unidad: 'kg', imagen: 'mza_gold.png', departamento: 'Frutas y Verduras' },
{id: 22, nombre: 'Manzana Golden Delicious', descripcion: 'Manzana Golden Delicious x kg', precio: 49.9, unidad: '1pz', imagen: 'mza_gold.png', departamento: 'Frutas y Verduras' },
{id: 23, nombre: 'Naranja Valencia', descripcion: 'Naranja Valencia x kg', precio: 34.9, unidad: '1pz', imagen: 'naranja_val.png', departamento: 'Frutas y Verduras' },
{id: 24, nombre: 'Nopal en penca limpio ', descripcion: 'Nopal en penca limpio x kg', precio: 39.9, unidad: '1pz', imagen: 'nopal_lim.png', departamento: 'Frutas y Verduras' },
{id: 25, nombre: 'Papaya Maradol ', descripcion: 'Papaya Maradol x kg', precio: 39.9, unidad: '1pz', imagen: 'papay_mara.png', departamento: 'Frutas y Verduras' },
{id: 26, nombre: 'Pepino ', descripcion: 'Pepino  x kg', precio: 26.9, unidad: '1pz', imagen: 'pepino.png', departamento: 'Frutas y Verduras' },
{id: 27, nombre: 'Pera Bosc', descripcion: 'Pera Bosc x kg', precio: 69.9, unidad: '1pz', imagen: 'pera_bosc.png', departamento: 'Frutas y Verduras' },
{id: 28, nombre: 'Pimiento Morron Rojo', descripcion: 'Pimiento Morron Rojo', precio: 89.9, unidad: '1pz', imagen: 'pime_roj.png', departamento: 'Frutas y Verduras' },
{id: 29, nombre: 'Pimiento Morron Verde', descripcion: 'Pimiento Morron Verde', precio: 79.9, unidad: '1pz', imagen: 'pime_ver.png', departamento: 'Frutas y Verduras' },
{id: 30, nombre: 'Platano Chiapas', descripcion: 'Platano Chiapas', precio: 24.9, unidad: 'kg', imagen: 'plat.png', departamento: 'Frutas y Verduras' },
{id: 31, nombre: 'Sandia', descripcion: 'Sandia x kg', precio: 11.9, unidad: '1pz', imagen: 'sandia.png', departamento: 'Frutas y Verduras' },
{id: 32, nombre: 'Tomate Bola', descripcion: 'Tomate Bola x kg', precio: 39.9, unidad: '1pz', imagen: 'tomat_bol.png', departamento: 'Frutas y Verduras' },
{id: 33, nombre: 'Tomate Saladet ', descripcion: 'Tomate Saladet x kg', precio: 29.9, unidad: '1kg', imagen: 'tomat_sal.png', departamento: 'Frutas y Verduras' },
{id: 34, nombre: 'Zanahoria ', descripcion: 'Zanahoria  x kg', precio: 16.9, unidad: '1pz', imagen: 'zanah.png', departamento: 'Frutas y Verduras' },
{id: 35, nombre: 'Huevo blanco San Juan 18 pzas', descripcion: 'Huevo blanco San Juan 18 pzas', precio: 57.9, unidad: '1pz', imagen: 'huevo_sj.png', departamento: 'Huevos' },
{id: 36, nombre: 'Danonino Napolitano', descripcion: 'Danonino Napolitano 252 grs', precio: 41.9, unidad: '1pz', imagen: 'danonino_6.png', departamento: 'Lacteos' },
{id: 37, nombre: 'Leche entera LALA ', descripcion: 'Leche entera uht LALA 6 lts', precio: 149.9, unidad: '6lts', imagen: 'leche_6lt.png', departamento: 'Lacteos' },
{id: 38, nombre: 'Mantequilla s/sal La Gloria', descripcion: 'Mantequilla s/sal La Gloria 90 GRS', precio: 29.9, unidad: '1pz', imagen: 'marga_gloria.png', departamento: 'Lacteos' },
{id: 39, nombre: 'Mantequilla s/sal La Gloria', descripcion: 'Mantequilla s/sal La Gloria 4 barras', precio: 105.9, unidad: '1pz', imagen: 'marga_gloria2.png', departamento: 'Lacteos' },
{id: 40, nombre: 'Margarina CHILCHOTA', descripcion: 'Margarina c/sal CHILCHOTA 400 grs', precio: 31.9, unidad: 'pz', imagen: 'marga_chil.png', departamento: 'Lacteos' },
{id: 41, nombre: 'Carne molida', descripcion: 'Carne molida de Sirlon Premium', precio: 266.9, unidad: 'kg', imagen: 'carne_mol.png', departamento: 'Carnes' },
{id: 42, nombre: 'Vampiros de pulpa negra', descripcion: 'Vampiros de pulpa negra', precio: 239.9, unidad: '1pz', imagen: 'vampir_pn.png', departamento: 'Carnes' },
{id: 43, nombre: 'Plato pastelero', descripcion: 'Plato pastelero Mimarca # 6 20pzas', precio: 22.9, unidad: 'pz', imagen: 'pla_ter.png', departamento: 'Desechables' },
{id: 44, nombre: 'Aceite Canola CAPULLO', descripcion: 'Aceite Canola CAPULLO', precio: 34.9, unidad: '1pz', imagen: 'aceite_cap.png', departamento: 'Despensa' },
{id: 45, nombre: 'Arroz CAZEROLA', descripcion: 'Arroz CAZEROLA 907 grs', precio: 22.9, unidad: 'pz', imagen: 'arroz_caze.png', departamento: 'Despensa' },
{id: 46, nombre: 'Azucar Estandar Mimarca', descripcion: 'Azucar Estandar Mimarca 907 grs', precio: 34.9, unidad: '1pz', imagen: 'azucar_mm.png', departamento: 'Despensa' },
{id: 47, nombre: 'Caldo Costilla Jugosa KNORR ', descripcion: 'Consomes Caldo Costilla Jugosa KNORR 8 pzas', precio: 27.9, unidad: '1pz', imagen: 'cost_knorr.png', departamento: 'Despensa' },
{id: 48, nombre: 'Caldo de Pollo KNORR', descripcion: 'Consomes Caldo de Pollo KNORR 12 pzas', precio: 317.9, unidad: '1pz', imagen: 'caldop_knorr.png', departamento: 'Despensa' },
{id: 49, nombre: 'Cereal Corn Flakes KELLOGGS ', descripcion: 'Cereal Corn Flakes KELLOGGS 410 grs', precio: 44.9, unidad: '1pz', imagen: 'cereal_kg.png', departamento: 'Despensa' },
{id: 50, nombre: 'Galleta Marias GAMESA', descripcion: 'Galleta Marias GAMESA 510 grs', precio: 41.9, unidad: '1pz', imagen: 'gallet_mar.png', departamento: 'Despensa' },
{id: 51, nombre: 'Mi Arroz Blanco KNORR ', descripcion: 'Sasonador Mi Arroz Blanco KNORR 48 grs', precio: 317.9, unidad: '1pz', imagen: 'miarroz_knorr.png', departamento: 'Despensa' },
{id: 52, nombre: 'Servilletas Practica PETALO', descripcion: 'Servilletas Practica PETALO', precio: 15.9, unidad: '1pz', imagen: 'servil_peta.png', departamento: 'Despensa' },
{id: 53, nombre: 'TANG Limonada', descripcion: 'Bebida en polvo Limonada TANG 13grs', precio: 5.5, unidad: '1pz', imagen: 'tang_lim.png', departamento: 'Despensa' },
{id: 54, nombre: 'TANG Naranja', descripcion: 'Bebida en polvo Naranja TANG 13grs', precio: 5.5, unidad: '1pz', imagen: 'tang_nar.png', departamento: 'Despensa' },
{id: 55, nombre: 'TANG Tamarindo', descripcion: 'ebida en polvo Tamarindo TANG 13 grs', precio: 5.5, unidad: 'pz', imagen: 'tang_tam.png', departamento: 'Despensa' },
{id: 56, nombre: 'TANG Tamarindo', descripcion: 'Bebida en polvo Manzana TANG 13grs', precio: 5.5, unidad: '1pz', imagen: 'tang_mza.png', departamento: 'Despensa' },
{id: 57, nombre: 'Chorizo Las Sevillanas', descripcion: 'Chorizo Las Sevillanas', precio: 12.9, unidad: 'pz', imagen: 'chor_sev.png', departamento: 'Embutidos' },
{id: 58, nombre: 'Bolsa p/basura COSTALITOS', descripcion: 'Bolsa p/basura G 62x80 COSTALITOS', precio: 34.9, unidad: 'pz', imagen: 'costal.png', departamento: 'Limpieza' },
{id: 59, nombre: 'Detergente en polvo ACE ', descripcion: 'Detergente en polvo ACE 540 grs', precio: 25.9, unidad: '1pz', imagen: 'deter_ace.png', departamento: 'Limpieza' },
{id: 60, nombre: 'FABULOSO Lavanda', descripcion: 'Limpiador Liq Lavanda FABULOSO 1lt', precio: 27.9, unidad: '1pz', imagen: 'fabuloso_lavn.png', departamento: 'Limpieza' },
{id: 61, nombre: 'FABULOSO Lavanda 2Lt', descripcion: 'Limpiador Liq Lavanda FABULOSO 2lt', precio: 36.9, unidad: '1pz', imagen: 'fabuloso_lavn2.png', departamento: 'Limpieza' },
{id: 62, nombre: 'FABULOSO Mar Fresco', descripcion: 'Limpiador Liq Mar Fresco FABULOSO 1lt', precio: 43.9, unidad: '1pz', imagen: 'fabuloso_fres.png', departamento: 'Limpieza' },
{id: 63, nombre: 'FABULOSO Naranja', descripcion: 'Limpiador Liq Naranja FABULOSO 1lt', precio: 27.9, unidad: '1pz', imagen: 'fabuloso_nar.png', departamento: 'Limpieza' },
{id: 64, nombre: 'Jabon barra blanco ZOTE ', descripcion: 'Jabon barra blanco ZOTE 200 grs', precio: 9.9, unidad: '1pz', imagen: 'zote_bco.png', departamento: 'Limpieza' },
{id: 65, nombre: 'Filete de Mojarra ', descripcion: 'Filete de Mojarra x kg', precio: 169.9, unidad: '1pz', imagen: 'filet_moj.png', departamento: 'Pescados' },
{id: 66, nombre: 'Cheez Whiz KRAFT ', descripcion: 'Cheez Whiz KRAFT 235 grs', precio: 59.9, unidad: '1pz', imagen: 'cheez_whiz.png', departamento: 'Quesos' },
{id: 67, nombre: 'Queso Manchego Rallado LALA ', descripcion: 'Queso Manchego Rallado LALA 250 grs', precio: 79.9, unidad: '1pz', imagen: 'qso_rall.png', departamento: 'Quesos' },
{id: 68, nombre: 'Queso Panela Canastita LA VILLITA ', descripcion: 'Queso Panela Canastita LA VILLITA 200 grs', precio: 79.9, unidad: '1pz', imagen: 'qso_pan.png', departamento: 'Quesos' },
{id: 69, nombre: 'Queso PHILADELFIA', descripcion: 'Queso crema PHILADELFIA', precio: 34.9, unidad: 'pz', imagen: 'ques_fil.png', departamento: 'Quesos' },
{id: 70, nombre: 'Sabritas Papas', descripcion: 'Sabritas Papas', precio: 52.9, unidad: 'pz', imagen: 'sabritas_pap.png', departamento: 'Snacks' },
{id: 71, nombre: 'Ensueño Fresca Prim', descripcion: 'Suavizante Ensueño Fresca Primavera', precio: 14.9, unidad: 'pz', imagen: 'sua_ensue.png', departamento: 'Suavizantes' },
{id: 72, nombre: 'Yakoult 80 ml ', descripcion: 'Yakoult 80 ml light', precio: 49.9, unidad: '1pz', imagen: 'yakul_lig.png', departamento: 'Yoghourt' },
{id: 73, nombre: 'Yakoult Lactofermentada', descripcion: 'Yakoult Lactofermentada 5 pzas', precio: 37.9, unidad: '1pz', imagen: 'yakul.png', departamento: 'Yoghourt' },
{id: 74, nombre: 'Yogourt LALA Manzana', descripcion: 'Yogourt LALA Manzana', precio: 40.9, unidad: 'pz', imagen: 'you_mza.png', departamento: 'Yoghourt' },

];

export default productos;
